/*
 * ScanUnkownReportDialog.java
 *
 * Created on 1. Januar 2002, 12:42
 */

package core;

import java.awt.datatransfer.*;


/**
 *
 * @author  Gerrit Gehnen
 */
public class ScanUnkownReportDialog extends javax.swing.JDialog {

    Clipboard clipbrd=getToolkit().getSystemClipboard();
    /** Creates new form ScanUnkownReportDialog */
    public ScanUnkownReportDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane ().setDefaultButton (closeButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        reportArea = new javax.swing.JTextArea();
        HeaderPanel = new javax.swing.JPanel();
        rowOneLabel = new javax.swing.JLabel();
        rowTwoLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        copyButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.BorderLayout(0, 5));

        setTitle("Unkown Devices found!");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 200));
        reportArea.setPreferredSize(new java.awt.Dimension(200, 172));
        jScrollPane1.setViewportView(reportArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        HeaderPanel.setLayout(new java.awt.GridLayout(2, 0, 5, 0));

        HeaderPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        rowOneLabel.setText("The following unkown devices are found!");
        HeaderPanel.add(rowOneLabel);

        rowTwoLabel.setText("Please send an email to <jsynthlib@overwhelmed.org> and include the following report.");
        HeaderPanel.add(rowTwoLabel);

        getContentPane().add(HeaderPanel, java.awt.BorderLayout.NORTH);

        copyButton.setText("Copy report to clipboard");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(copyButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        StringSelection text=new StringSelection(reportArea.getText());
        clipbrd.setContents(text,text);
    }//GEN-LAST:event_copyButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
           setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public void addToReport(java.lang.String text) {
        reportArea.append(text);
        reportArea.updateUI();
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rowOneLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel rowTwoLabel;
    private javax.swing.JButton copyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reportArea;
    // End of variables declaration//GEN-END:variables

}
