#!/bin/bash
echo Compiling...
for n in LinuxCharDevMidiProvider/*.java; do javac -g $n; done
echo Building jar...
jar cf ../LinuxCharDev.jar META-INF/services/javax.sound.midi.spi.MidiDeviceProvider LinuxCharDevMidiProvider/*.class
echo Done.
